### ISSUE TITLE
Improve:简化word.CamelCaseToUnderscore内部逻辑判断

### ISSUE THREAD

**Issue by yuchanns** [go-programming-tour-book/tour#1]
https://github.com/go-programming-tour-book/tour/blob/4217581d59cea4f8bdc95ed561cb2fb34a1ce6b0/internal/word/word.go#L27-L40

发现word.CamelCaseToUnderscore的代码可以进一步简化，稍后提交pr

**Comment by eddycjy** [comment]
已收到，具体会等过段时间后统一整理 feature。
