### ISSUE TITLE
拼写错误_目录路径为strcut，但结构体英文为struct，望修正

### ISSUE THREAD

**Issue by OctopusLian** [go-programming-tour-book/tour#4]
拼写错误，有时会导致读者可能默认`struct`，结果编译时发现引用了`strcut`包却没有用的低级错误。

**Comment by eddycjy** [comment]
感谢反馈，本项目已经修复，书籍的话将会在第三次重印时解决。

**Comment by SashiRin** [comment]
https://github.com/go-programming-tour-book/tour/blob/master/internal/sql2struct/template.go 里的`strcutTql`是不是也应该是`structTql`？
